### ISSUE TITLE
Problem parsing METAR date/time at month rollover

### ISSUE THREAD

**Issue by douglasr** [joeyates/metar-parser#43]
There is a date wrapping problem when a METAR issued just before midnight UTC of a month rollover is parsed shortly after month rollover. For example, the following METAR was issued at 2359 UTC on March 31st:

    METAR OPPS 312359Z 23006KT 4000 HZ SCT040 SCT100 17/12 Q1011

but then parsed at 00:02:11 UTC on 01 Apr (about three minutes after it was issued). The call to Parser.time() returns May 01 23:59 UTC, which is a result of trying to construct April 31st when the call is made to Time.gm() which then corrects the date to the equivalent of April 31, which is May 1.

@joeyates : I'm going to add some logic to handle this month end (and probably year end also) but I wondered if you had any thoughts about this in terms of how you would like it handled? That way you can simply use my pull request (when I submit it).

Cheers,
Douglas

**Comment by joeyates** [comment]
I've done 2 things:
* forced UTC parsing of the full YYYYMMDD etc string received by the Raw module,
* created a branch with an added spec example: feature/fix-month-rollover-flaw

Unfortunately, the spec passes - I was hoping it would reproduce the problem you saw.

Any ideas what I'm doing wrong in my repro?

**Comment by douglasr** [comment]
I'll have to look at it again but when this came up I have tracked it back to this line in /lib/metar/parser.rb:
`Time.gm(@raw.time.year, @raw.time.month, @day, @hour, @minute)`
which is using the day, hour and minute parsed from the METAR and then applying it to the current year/month.

Here is code to replicate this:
`
Timecop.freeze(DateTime.new(2016,4,1,0,2,0))
metar_s = "CYBW 312300Z AUTO 28003KT 240V050 9SM BKN170 BKN190 OVC220 07/M01 A2977 RMK SLP107 DENSITY ALT 4000FT="
d = Metar::Raw::Data.new(metar_s)
parser = Metar::Parser.new(d)
parsed_time = parser.time
`

You will see that the time is parsed as `2016-05-01 23:00:00 UTC `

**Comment by joeyates** [comment]
A code example that does *not* have the same problem would be where the time of the report is supplied to `Metar::Raw::Data.new` as its second parameter:

```ruby
Timecop.freeze(DateTime.new(2016,4,1,0,2,0))
metar_s = "CYBW 312300Z AUTO 28003KT 240V050 9SM BKN170 BKN190 OVC220 07/M01 A2977 RMK SLP107 DENSITY ALT 4000FT="
report_time = Time.parse("2016/03/31 23:59 UTC")
d = Metar::Raw::Data.new(metar_s, report_time) # <- added report_time here
parser = Metar::Parser.new(d)
parsed_time = parser.time
```

Here, the parser reports the time as `2016-03-31 23:00:00 UTC`

I think the problem is that this second parameter is currently optional, and your example clarifies that it really shouldn't be - the parser needs to know the report time.

In fact, if you use Metar::Raw::Noaa, that's what happens - the time from the report is used and is available to the parser.

I'm thinking of transitioning to the time parameter being required - i.e. by initially adding a deprecation warning. Would that suit your use case? I.e. do you have the time of the report available?

**Comment by douglasr** [comment]
It's a bit of a catch-22 -- you need the time to properly parse the METAR but the day/time are in the METAR you are parsing. I'm using a quasi AFTN to pull the METAR so I have access to the transmission time from the sender. However a quick check of that time vs the METAR time around the turn of the hour revealed examples where the packets were sent just before the hour but reported as on the hour, which would also fail. As would observations just before the hour but reported one or after the hour. Something like this:

```
SACN59 CWAO 041457
METAR CYBW 041500Z AUTO 00000KT 9SM BKN130 02/M02 A2982 RMK SLP130=
```
and
```
SACN59 CWAO 041501
METAR CYBW 041500Z AUTO 00000KT 9SM BKN130 02/M02 A2982 RMK SLP130=
```
So if you roll it back to the end of the month it would look like this:
```
SACN59 CWAO 312357
METAR CYBW 010000Z AUTO 00000KT 9SM BKN130 02/M02 A2982 RMK SLP130=
```
and
```
SACN59 CWAO 010000
METAR CYBW 312359Z AUTO 00000KT 9SM BKN130 02/M02 A2982 RMK SLP130=
```
In both these cases the month/day of the report date would be different than the time of the transmission. I see the time you are talking about on the NOAA site, such as for CYBW here:

ftp://tgftp.nws.noaa.gov/data/observations/metar/stations/CYBW.TXT

but I feel like relying on that date within the NOAA FTP site is problematic given that there are other sources for METAR and since users may want to parse old or manually created METAR.

**Comment by douglasr** [comment]
I think that the Raw object, by nature of the name, shouldn't require a report date/time. Specifying a date/time seems to be more of a function of the parser since if you wanted to parse a METAR from last year you should be able to let the parser know that `291400` means November 29, 2015 as an example.

I'm fine to leave it at that and then require the user to handle the edge cases generated by month rollover UTC time. That said, I think you can make a case that if no `report_time` parameter is specified, that the current time is assumed and if it's within a few hours of the rollover that the library should handle the edge cases.

**Comment by joeyates** [comment]
I think a METAR string on its own is ambiguous, as it only specifies the day of the month. So I think the best thing to do is offer an interface that makes a best effort guess at the date, and name it as such.

So, I want to maintain the current `Metar::Raw::Data` class (and make the time parameter obligatory).

But also I'm intending adding `Metar::Raw::DataGuessDate` - with docs to explain how the guessing works.

I.e.

> # Metar::Raw::DataGuessDate
> This class decides the date of the reading by taking the "day of month" present in the METAR string and, based on the current time, choosing the nearest date with that "day of month".
> So, the following METAR:
```
OPPS 312359Z 23006KT 4000 HZ SCT040 SCT100 17/12 Q1011
```
> is treated as a reading from March 31st when analyzed on April 1st.
> Note however that the same METAR would be treated as being from May 1st when analyzed on 16th April.

**Comment by douglasr** [comment]
I think we're on the right track with this. One could make a case that if the analyze date and the METAR date are too far apart that an error should be thrown. You could also make a case that the date should always fall back up to the point where the month rollover is eminent, say in the last 24 hours before month end. That all said, your first thought might be a good middle ground.

If you check this into the branch, I'll pull it and start playing around with it before it's merged into the master.

**Comment by joeyates** [comment]
I've added the class `Metar::Raw::Metar` which decides the reading date of the METAR string according to the current date - it skips back to the previous day with the day of month carried by the datetime field in the METAR string.

I think the 2 main use cases are now handled:
1. when the user has a METAR string and its reading date,
2. when the user has a recent METAR string and wants the library to deduce the date.

**Comment by douglasr** [comment]
I've tested out your solution and it works as expected. I have a few ideas for handling similar edge cases but I think we can consider this fixed/closed now.

**Comment by joeyates** [comment]
If you open an issue detailing your ideas, I'd be happy to discuss them.
