### ISSUE TITLE
NoMethodError when parsing density altitude

### ISSUE THREAD

**Issue by douglasr** [joeyates/metar-parser#44]
NoMethodError is being raised when parsing a METAR with a density altitude, such as:

`METAR CYBW 010000Z AUTO VRB04KT 9SM SCT070 13/M01 A3028 RMK SLP282 DENSITY ALT 4100FT=`

```ruby
NoMethodError: undefined method `[]' for nil:NilClass
	from .rvm/gems/ruby-2.2.1/bundler/gems/metar-parser-b3786bf13c39/lib/metar/data.rb:627:in `parse'
```

If you remove the density altitude from the METAR then it is parsed as per normal.

**Comment by joeyates** [comment]
Thanks for the report.

The trailing '=' was confusing things. I've changed the parsing so that it is ignored.
I've released version 1.2.1 with the fix.
