### ISSUE TITLE
Parser fails on last chunk when end of METAR character (=) encountered

### ISSUE THREAD

**Issue by douglasr** [joeyates/metar-parser#48]
If an end of METAR character (=) immediately follows the last chunk (and there is no remarks section) then the last chunk fails to be parsed. For example, in both the following cases, the last chunk is left as "unparsed":

`METAR LPPT 070530Z 34003KT 310V010 CAVOK 14/12 Q1013=`
`METAR YMML 080800Z 17007KT CAVOK 13/05 Q1020 NOSIG=`

However, if there is a space between the last chunk and the = character or there is a remarks section then only the = character is listed as unparsed. For example:

`METAR LPPT 070500Z 33004KT CAVOK 14/12 Q1013 =`
`METAR CYBW 070500Z AUTO 14007KT 9SM OVC027 01/M07 A3018 RMK SLP265=`

In both these cases, the complete core data in the METAR is parsed, though in the second example the sea level pressure of the remarks, which should be parsed, is not parsed -- again due to the = character.

It seems that the best course of action here is to drop the = character if it's at the end of the METAR since it is part of the specification. If you advise on how you'd like to proceed I can code up a pull request.

**Comment by joeyates** [comment]
Thanks for the report.

I've released 'v1.3.1' with this fix.
