### ISSUE TITLE
offer to help maintain

### ISSUE THREAD

**Issue by tkrajcar** [joeyates/metar-parser#54]
Hi @joeyates,

I'm working on some production software using this gem, and wanted to offer to help support you since I'll be depending on this gem for the near future and I figured you might be interested in a hand after going it solo for 7 years :)

No pressure - if you're not interested, feel free to close.

**Comment by joeyates** [comment]
Hello @tkrajcar,

Thanks for the offer. Let's work via PRs for now and see how it goes, OK?
