### ISSUE TITLE
Parser gives up if invalid winds present

### ISSUE THREAD

**Issue by tkrajcar** [joeyates/metar-parser#57]
Given the following real METAR that's current:
`KSEE 181947Z 000000KT 10SM SKC 22/10 A2999`

The parser appears to give up on parsing or returning anything after the winds; sea_level_pressure, temperature, etc are all blank.

Unfortunately, I have learned that it's annoyingly common for real-world METARs to have incorrectly-formatted winds; it would be nice if the parser would not bail out in these cases.

**Comment by joeyates** [comment]
Thanks for the report. As you state, the wind data `000000KT` is incorrect (it should have 5 zeroes and not six).

I think this is a valid case for 'loose mode', so I've added it. In strict mode it will continue to fail to parse, of course.

**Comment by joeyates** [comment]
Released as v1.4.3

**Comment by tkrajcar** [comment]
Awesome, thanks! Looks great.
